nav:
    - Home: /docs/
    - Tutorial: /docs/getting-started/
    - Concepts: /docs/concepts/
    - Installing: /docs/install/
    - Functions: /docs/functions/
    - Serving: /docs/serving/
    - Eventing: /docs/eventing/
    - Knative CLI: /docs/client/
    - Code samples: /docs/samples/
    - Reference: /docs/reference/security/
  #####################################################
    # Blog
  #####################################################
    - Blog:
      - index.md
      - Releases:
          - releases/announcing-knative-v1-14-release.md
          - releases/announcing-knative-v1-13-release.md
          - releases/announcing-knative-v1-12-release.md
          - releases/announcing-knative-v1-11-release.md
          - releases/announcing-knative-v1-10-release.md
          - releases/announcing-knative-v1-9-release.md
          - releases/announcing-knative-v1-8-release.md
          - releases/announcing-knative-v1-7-release.md
          - releases/announcing-knative-v1-6-release.md
          - releases/announcing-knative-v1-5-release.md
          - releases/announcing-knative-v1-4-release.md
          - releases/announcing-knative-v1-3-release.md
          - releases/announcing-knative-v1-2-release.md
          - releases/announcing-knative-v1-1-release.md
          - releases/announcing-knative-v1-0-release.md
          - releases/knative-1.0.md
          - releases/announcing-knative-1.0.md
          - releases/announcing-knative-v0-26-release.md
          - releases/announcing-knative-v0-25-release.md
          - releases/announcing-knative-v0-24-release.md
          - releases/announcing-knative-v0-23-release.md
          - releases/announcing-knative-v0-22-release.md
          - releases/announcing-knative-v0-21-release.md
          - releases/announcing-knative-v0-20-release.md
          - releases/announcing-knative-v0-19-release.md
          - releases/announcing-knative-v0-18-release.md
          - releases/announcing-knative-v0-17-release.md
          - releases/announcing-knative-v0-5-release.md
          - releases/announcing-knative-v0-4-release.md
          - releases/announcing-knative-v0-3-release.md
          - releases/announcing-knative-v0-2-release.md
      - Articles:
          - articles/aws_to_func_migration.md
          - articles/consuming_s3_data_with_knative.md
          - articles/How-IBM-watsonx-Assistant-uses-Knative-Eventing-to-train-machine-learning-models.md
          - articles/enhancing-the-knative-experience.md
          - articles/knative-meets-apache-camel.md
          - articles/knative-backstage-plugins.md
          - articles/demystifying-activator-on-path.md
          - articles/knative-eventing-vision.md
          - articles/new_event_discovery_features.md
          - articles/getting-started-blog-p3.md
          - articles/getting-started-blog-p2.md
          - articles/getting-started-blog-p1.md
          - articles/getting-started-blog-p0.md
          - articles/improved-ha-configuration.md
          - articles/from-cloudevent-to-apache-kafka-records-part-two.md
          - articles/knative-serving-in-k0s.md
          - articles/from-cloudevent-to-apach-kafka-records-part-one.md
          - articles/kafka-broker-with-isolated-data-plane.md
          - articles/single-node-kafka-development.md
          - articles/eventing-rabbitmq-announcement.md
          - articles/performance-test-with-slos.md
          - articles/workflow-as-function-flow.md
          - articles/highlighting-value-knative-c-suite.md
          - articles/quickstart-with-knative.md
          - articles/distributed-tracing.md
          - articles/event-drive-app-knative-eventing-kogito.md
          - articles/orchestrating-cloud-events-with.md
          - articles/event-driven-image-bigquery-processing-pipelines.md
          - articles/get-started-knative-eventing.md
          - articles/knative-v0-3-autoscaling-a-love-story.md
          - articles/ko-fast-kubernetes-microservice-development-in-go.md
          - articles/build-deploy-manage-modern-serverless-workloads-using-knative-on-kubernetes.md
      - Steering Committee:
          - steering/2024-02-14-trademark-committee-dissolved.md
          - steering/toc-2022-election-announcement.md
          - steering/2022-04-14-annual-report-2021.md
          - steering/knative-and-endusers.md
          - steering/cncf.md
          - steering/knative-cncf-donation.md
          - steering/2021-end-user-election.md
          - steering/2021-12-14-steering-elections-results.md
          - steering/steering-elections-2021.md
          - steering/toc-2021-election-announcement.md
          - steering/2020-11-ksc-elections.md
          - steering/governance-changes.md
          - steering/2020-05-toc_election_results.md
          - steering/2020-01-annual-report-2019.md
          - steering/2019-12-updates.md
      - Events:
          - events/security-audit-2023.md
          - events/knative-at-kubecon-na-2023.md
          - events/fuzzing-audit-2023.md
          - events/knative-projectmeeting-kubecon-eu-2023.md
          - events/google-summer-of-code-2023.md
          - events/virtual-office-hour-12-2022.md
          - events/knative-at-kubecon-na-2022.md
          - events/google-summer-of-code-2022.md
          - events/install-fest-04-2022.md
          - events/knative-at-kubecon-eu-2019.md
          - events/knative-at-kubecon-seattle.md
    #####################################################          
    # keep the same order as on the main page
    - About: /docs/about/testimonials/
    - Community: /docs/community/
