# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

ignored = [
  "github.com/knative/docs/serving/samples/grpc-ping-go*",
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
