apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-shell
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/helloworld-shell
        env:
        - name: TARGET
          value: "Shell Sample v1"
