apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-csharp
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/helloworld-csharp
        env:
        - name: TARGET
          value: "C# Sample v1"
