apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-dart
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/{username}/helloworld-dart
          env:
          - name: TARGET
            value: "Dart Sample v1"
