apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-java-spring
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/helloworld-java-spring
        env:
        - name: TARGET
          value: "Spring Boot Sample v1"
