plugins:
  redirects:
    redirect_maps:
      serving/spec/knative-api-specification-1.0.md: https://github.com/knative/specs/blob/main/specs/serving/knative-api-specification-1.0.md
      serving/feature-flags.md: admin/serving/feature-flags.md
      serving/using-subroutes.md: developer/serving/traffic-management.md
      serving/rolling-out-latest-revision.md: developer/serving/rolling-out-latest-revision.md
      serving/tag-resolution.md: developer/serving/tag-resolution.md
      serving/deploying-from-private-registry.md: developer/serving/deploying-from-private-registry.md
      serving/samples/blue-green-deployment.md: developer/serving/traffic-management.md
      serving/samples/traffic-splitting/README.md: developer/serving/traffic-management.md
      admin/install/install-eventing-with-yaml.md: admin/install/eventing/install-eventing-with-yaml.md
      admin/install/install-serving-with-yaml.md: admin/install/serving/install-serving-with-yaml.md
      client/connecting-kn-to-your-cluster/index.md: client/README.md
      concepts/overview.md: index.md
      eventing/broker/alternate/index.md: eventing/broker/README.md
      eventing/broker/broker-event-delivery.md: developer/eventing/event-delivery.md
      eventing/broker/configmaps/README.md: admin/eventing/broker-configuration.md
      eventing/broker/kafka-broker/kafka-configmap.md: admin/eventing/kafka-channel-configuration.md
      eventing/channels/default-channels/index.md: eventing/channels/README.md
      eventing/event-delivery.md: developer/eventing/event-delivery.md
      eventing/metrics.md: admin/collecting-metrics/eventing-metrics/metrics.md
      eventing/parallel.md: eventing/flows/parallel.md
      eventing/samples/apache-camel-source/index.md: developer/eventing/sources/apache-camel-source/README.md
      eventing/samples/gcp-pubsub-source/README.md: eventing/samples/cloud-pubsub-source/README.md
      eventing/samples/kubernetes-event-source/index.md: developer/eventing/sources/apiserversource/README.md
      eventing/samples/ping-source/index.md: developer/eventing/sources/ping-source/README.md
      eventing/samples/sequence/index.md: eventing/flows/sequence/README.md
      eventing/samples/sequence/sequence-replay-to-event-display/index.md: eventing/flows/sequence/sequence-reply-to-event-display/README.md
      eventing/samples/sequence/sequence-reply-to-sequence/index.md: eventing/flows/sequence/sequence-reply-to-sequence/README.md
      eventing/samples/sequence/sequence-terminal/index.md: eventing/flows/sequence/sequence-terminal/README.md
      eventing/samples/sequence/sequence-with-broker-trigger/index.md: eventing/flows/sequence/sequence-with-broker-trigger/README.md
      eventing/samples/sinkbinding/README.md: developer/eventing/sources/sinkbinding/README.md
      eventing/samples/writing-event-source-easy-way/index.md: developer/eventing/sources/creating-event-sources/writing-event-source-easy-way/README.md
      eventing/samples/writing-event-source/01-theory/index.md: developer/eventing/sources/creating-event-sources/writing-event-source/01-theory.md
      eventing/samples/writing-event-source/02-lifecycle-and-types/index.md: developer/eventing/sources/creating-event-sources/writing-event-source/02-lifecycle-and-types.md
      eventing/samples/writing-event-source/03-controller/index.md: developer/eventing/sources/creating-event-sources/writing-event-source/03-controller.md
      eventing/samples/writing-event-source/04-reconciler/index.md: developer/eventing/sources/creating-event-sources/writing-event-source/04-reconciler.md
      eventing/samples/writing-event-source/05-receive-adapter/index.md: developer/eventing/sources/creating-event-sources/writing-event-source/05-receive-adapter.md
      eventing/samples/writing-event-source/06-yaml/index.md: developer/eventing/sources/creating-event-sources/writing-event-source/06-yaml.md
      eventing/samples/writing-event-source/07-knative-sandbox/index.md: developer/eventing/sources/creating-event-sources/writing-event-source/07-knative-sandbox.md
      eventing/samples/writing-event-source/index.md: developer/eventing/sources/creating-event-sources/writing-event-source/README.md
      eventing/sequence.md: eventing/flows/sequence/README.md
      eventing/sink/README.md: developer/eventing/sinks/README.md
      eventing/sink/kafka-sink.md: developer/eventing/sinks/kafka-sink.md
      eventing/sources/apiserversource/index.md: developer/eventing/sources/apiserversource/README.md
      eventing/sources/pingsource/index.md: developer/eventing/sources/ping-source/README.md
      eventing/sources/containersource.md: developer/eventing/sources/containersource/README.md
      eventing/triggers/index.md: eventing/broker/triggers/README.md
      help/README.md: help/contributor/README.md
      install/README.md: admin/install/README.md
      install/check-install-version.md: check-install-version.md
      install/collecting-logs/index.md: admin/collecting-logs/README.md
      install/collecting-metrics/index.md: admin/collecting-metrics/README.md
      install/getting-started-knative-app/index.md: getting-started/README.md
      serving/getting-started-knative-app.md: getting-started/README.md
      install/install-eventing-with-yaml.md: admin/install/eventing/install-eventing-with-yaml.md
      # This doesn't exist anymore, we should probably replace it
      install/install-extensions.md: admin/install/README.md
      install/install-kn/index.md: client/install-kn.md
      install/install-serving-with-yaml.md: admin/install/serving/install-serving-with-yaml.md
      install/installation-files.md: admin/install/README.md
      install/installing-istio.md: admin/install/installing-istio.md
      install/knative-offerings.md: admin/install/knative-offerings.md
      install/knative-with-operators.md: admin/install/knative-with-operators.md
      install/operator/configuring-eventing-cr.md: admin/install/operator/configuring-eventing-cr.md
      install/operator/configuring-serving-cr.md: admin/install/operator/configuring-serving-cr.md
      install/prerequisites.md: admin/install/README.md
      operator/configuring-eventing-cr/index.md: admin/install/operator/configuring-eventing-cr.md
      operator/configuring-serving-cr/index.md: admin/install/operator/configuring-serving-cr.md
      reference/resources/index.md: client/README.md
      serving/autoscaling/autoscaling-concepts.md: serving/autoscaling/autoscaler-types.md
      serving/autoscaling/target-burst-capacity/index.md: serving/load-balancing/target-burst-capacity.md
      serving/configuring-autoscaling/index.md: serving/autoscaling/README.md
      serving/creating-domain-mappings.md: developer/serving/services/custom-domains.md
      serving/debugging-application-issues.md: developer/serving/troubleshooting/debugging-application-issues.md
      serving/metrics.md: admin/collecting-metrics/serving-metrics/metrics.md
      serving/samples/autoscale-go/index.md: serving/autoscaling/autoscale-go/README.md
      serving/services/README.md: developer/serving/services/README.md
      serving/services/creating-services.md: developer/serving/services/creating-services.md
      serving/services/deployment.md: admin/serving/deployment.md
      serving/services/private-services.md: developer/serving/services/private-services.md
      serving/using-an-ssl-cert/index.md: serving/using-a-tls-cert.md
      uninstall.md: admin/install/uninstall.md
      upgrade/index.md: admin/upgrade/README.md
      upgrade/upgrade-installation-with-operator.md: admin/upgrade/upgrade-installation-with-operator.md
      upgrade/upgrade-installation.md: admin/upgrade/upgrade-installation.md
