apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-php
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/helloworld-php
        env:
        - name: TARGET
          value: "PHP Sample v1"
