apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-clojure
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/{username}/helloworld-clojure
          env:
            - name: TARGET
              value: "Clojure Sample v1"
