apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-swift
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/{username}/helloworld-swift
          env:
          - name: TARGET
            value: "Swift"
