apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-apl
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/{username}/helloworld-apl
            env:
            - name: TARGET
              value: "APL Sample v1"
            - name: FUNC_HANDLER
              value: "halloWorld"
