apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-java-micronaut
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/helloworld-java-micronaut
        env:
        - name: TARGET
          value: "Micronaut Sample v1"
